package pdfgen

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// CourseReportRow — строка для отчёта по курсу.
type CourseReportRow struct {
	StudentName     string
	AssignmentTitle string
	Score           float64
	MaxScore        float64
	GradedAt        time.Time
}

type CourseReport struct {
	CourseTitle   string
	TeacherName   string
	GeneratedAt   time.Time
	StudentsCount int
	AvgScore      float64
	Rows          []CourseReportRow
}

// BuildCourseReportPDF — рендерит отчёт по курсу в PDF и возвращает байты.
func BuildCourseReportPDF(r CourseReport) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.AddPage()

	// Заголовок
	pdf.SetFont("Arial", "B", 18)
	pdf.SetTextColor(30, 30, 30)
	pdf.Cell(0, 10, "SmartCourse — Course Report")
	pdf.Ln(12)

	// Метаданные
	pdf.SetFont("Arial", "", 11)
	pdf.SetTextColor(80, 80, 80)
	pdf.Cell(0, 6, fmt.Sprintf("Course: %s", r.CourseTitle))
	pdf.Ln(6)
	pdf.Cell(0, 6, fmt.Sprintf("Teacher: %s", r.TeacherName))
	pdf.Ln(6)
	pdf.Cell(0, 6, fmt.Sprintf("Generated: %s", r.GeneratedAt.Format("2006-01-02 15:04")))
	pdf.Ln(10)

	// Сводка
	pdf.SetFillColor(240, 245, 255)
	pdf.SetFont("Arial", "B", 12)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(60, 10, "Students", "1", 0, "C", true, 0, "")
	pdf.CellFormat(60, 10, "Average score", "1", 0, "C", true, 0, "")
	pdf.CellFormat(60, 10, "Grades total", "1", 1, "C", true, 0, "")

	pdf.SetFont("Arial", "", 12)
	pdf.CellFormat(60, 10, fmt.Sprintf("%d", r.StudentsCount), "1", 0, "C", false, 0, "")
	pdf.CellFormat(60, 10, fmt.Sprintf("%.1f%%", r.AvgScore), "1", 0, "C", false, 0, "")
	pdf.CellFormat(60, 10, fmt.Sprintf("%d", len(r.Rows)), "1", 1, "C", false, 0, "")
	pdf.Ln(8)

	// Таблица оценок
	pdf.SetFont("Arial", "B", 11)
	pdf.SetFillColor(230, 230, 230)
	pdf.CellFormat(55, 8, "Student", "1", 0, "L", true, 0, "")
	pdf.CellFormat(75, 8, "Assignment", "1", 0, "L", true, 0, "")
	pdf.CellFormat(25, 8, "Score", "1", 0, "C", true, 0, "")
	pdf.CellFormat(25, 8, "Date", "1", 1, "C", true, 0, "")

	pdf.SetFont("Arial", "", 10)
	for i, row := range r.Rows {
		fill := i%2 == 0
		pdf.SetFillColor(248, 248, 248)
		pdf.CellFormat(55, 7, truncate(row.StudentName, 30), "1", 0, "L", fill, 0, "")
		pdf.CellFormat(75, 7, truncate(row.AssignmentTitle, 42), "1", 0, "L", fill, 0, "")
		score := fmt.Sprintf("%.0f / %.0f", row.Score, row.MaxScore)
		pdf.CellFormat(25, 7, score, "1", 0, "C", fill, 0, "")
		pdf.CellFormat(25, 7, row.GradedAt.Format("2006-01-02"), "1", 1, "C", fill, 0, "")
	}

	pdf.Ln(10)
	pdf.SetFont("Arial", "I", 9)
	pdf.SetTextColor(150, 150, 150)
	pdf.Cell(0, 5, "Generated by SmartCourse")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func truncate(s string, n int) string {
	if len([]rune(s)) <= n {
		return s
	}
	r := []rune(s)
	return string(r[:n-1]) + "…"
}
